### ISSUE TITLE
Can we send Asset/NFT in transaction using this project.

### ISSUE THREAD

**Issue by hussamBim** [dendorferpatrick/nami-wallet-examples#11]
Can we send Asset/NFT in transaction using this project.

**Comment by dendorferpatrick** [comment]
Yes, you also can send assets with the code. Just include the assets in the `nami.transaction` function.
` assets: [{unit:"5612bdcde30b1edf25823f62aa73c1b06831fb0f406c6c812da455db.TestNft", quantity: "1"}])`

**Comment by hussamBim** [comment]
I did this by reading your repo. Thanks for your response.
