### ISSUE TITLE
npm run build is showing number of issues.

### ISSUE THREAD

**Issue by mailtodanish** [dendorferpatrick/nami-wallet-examples#4]
npm run build is showing number of issues.

**Comment by dendorferpatrick** [comment]
Hi, I added the build command with `webpack` ([b9782827ef05498f18d8ce016a7203dc0bcc5cd0](https://github.com/dendorferpatrick/nami-wallet-examples/commit/b9782827ef05498f18d8ce016a7203dc0bcc5cd0)). When I run `npm run build` everything builds fine.
